-- ============================================================================
--  CREACIÓN DE ROLES / USUARIOS
-- ============================================================================

-- Desde SYSDBA
GRANT ALTER ANY TABLE TO NARANJO_ADMIN;

-- A) USUARIO PROPIETARIO 
CREATE USER NARANJO_ADMIN IDENTIFIED BY AdminPass123
DEFAULT TABLESPACE USERS 
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO NARANJO_ADMIN;

-- B) USUARIO DE APLICACIÓN (El que usare - Spring Boot)
-- IMPORTANTE: QUOTA 0M impide que este usuario cree tablas propias por error.
CREATE USER NARANJO_APP IDENTIFIED BY AppPass123
DEFAULT TABLESPACE USERS
QUOTA 0M ON USERS; 

GRANT CREATE SESSION TO NARANJO_APP;

-- ============================================================================
--  ASIGNACIÓN DE PERMISOS (Grants)
-- ============================================================================
-- Doy permiso a NARANJO_APP para leer/escribir en las tablas de NARANJO_ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON NARANJO_ADMIN.PERSONA TO NARANJO_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON NARANJO_ADMIN.DATOS_FISCALES TO NARANJO_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON NARANJO_ADMIN.ARTICULO TO NARANJO_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON NARANJO_ADMIN.COMPRA TO NARANJO_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON NARANJO_ADMIN.LINEA_COMPRA TO NARANJO_APP;
GRANT SELECT ON NARANJO_ADMIN.GLOBAL_SEQ TO NARANJO_APP;
GRANT CREATE SYNONYM TO NARANJO_APP;

--Ejecutar desde NARANJO_APP para crear sinónimos y facilitar el acceso a las tablas
CREATE OR REPLACE SYNONYM PERSONA FOR NARANJO_ADMIN.PERSONA;
CREATE OR REPLACE SYNONYM DATOS_FISCALES FOR NARANJO_ADMIN.DATOS_FISCALES;
CREATE OR REPLACE SYNONYM ARTICULO FOR NARANJO_ADMIN.ARTICULO;
CREATE OR REPLACE SYNONYM COMPRA FOR NARANJO_ADMIN.COMPRA;
CREATE OR REPLACE SYNONYM LINEA_COMPRA FOR NARANJO_ADMIN.LINEA_COMPRA;
CREATE OR REPLACE SYNONYM GLOBAL_SEQ FOR NARANJO_ADMIN.GLOBAL_SEQ;

COMMIT;